CREATE TABLE friends (
id INT,
user_a INT NOT NULL,
user_b INT NOT NULL
);

ALTER TABLE friends ADD PRIMARY KEY (id);
ALTER TABLE friends MODIFY id INT AUTO_INCREMENT;
ALTER TABLE friends ADD CONSTRAINT fk_user_a FOREIGN KEY (user_a) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE friends ADD CONSTRAINT fk_user_b FOREIGN KEY (user_b) REFERENCES users(id) ON DELETE CASCADE;